Fix inject_ia_markup_meta_tag() to use is_singular() and get_the_ID()
Automattic/fb-instant-articles pull request #954
Opened 2018-06-29 17:43 UTC by jerclarke

re: #953

Small fix to ensure that before inserting the `ia:markup_url` meta tag, we check that we're on a single-post screen. 
Also uses with `get_post(get_the_ID())` rather than relying on globals (no argument) so that we always have the righ tpost.

This PR:

* [x] 
* [ ] 
* [ ] 

Follows #

Relates to #

Fixes #

2021-05-09 09:18 UTC, ahr36 approved these changes

2022-09-23 10:38 UTC, GaryJones requested changes

2022-09-23 10:38 UTC, GaryJones commented on facebook-instant-articles.php
> +		$post = get_post( get_queried_object_id() );
Under what conditions would this now give a different result than it did before? Can you add an integration test to cover it?

2022-09-23 10:38 UTC, GaryJones commented on facebook-instant-articles.php
> +			return;
```suggestion
		if ( ! is_singular() ) {
			return;
		}
```

2022-10-16 02:37 UTC, GaryJones commented
Closing for lack of feedback.

2022-10-16 02:37 UTC, closed without merging